Add edit events ld
peyton-lalli/swe5-project-v3frontend pull request #19
Opened 2023-02-25 02:43 UTC by LoganDemaray316

Adds the Edit Events popup that can be used for Juries and Recitals. A start and end time can be passed with intervals that can make a list of buttons for that times the student can choose from.

Edited Files:
EventComponent.vue

Added Files:
EventItemEdit.vue

2023-02-25 03:22 UTC, ethanimooney requested changes

2023-02-25 03:22 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +                    variant="solo"></v-text-field>
Look at the Vuetify docs for Text Fields, particularly 'Append Icon' to get the search icon here.

2023-02-25 03:22 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +      timesToResults(start_time, end_time, interval) {
```
function getTimeSlots(startDate, endDate, interval) {
  var slots = [];

  var intervalMillis = interval * 60 * 1000;

  while (startDate < endDate) {
    var mins = (startDate.getMinutes() + "0").slice(0, 2);
    slots.push(startDate.getHours() + ":" + mins);
    startDate.setTime(startDate.getTime() + intervalMillis);
  }

  return slots;
}
```

Code above does the same thing, just using the JS Date datatype. We should be able to parse our database call into Dates so this seems more efficient if you want to change it.

2023-02-25 03:22 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +                  >//Addition Selections Go Here</v-card
Some typos/random text here?

2023-02-25 03:22 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +                      <v-card class="fullBorderCurve">
Same here, can use `rounded-lg` instead of that class.

2023-02-25 03:22 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +                  <v-card class="eventsGradient fullBorderCurve mainblur">
Same here, can use `rounded-lg` instead of that class.

2023-02-25 05:38 UTC, LoganDemaray316 commented on src/components/EventItemEdit.vue
> +    <v-card class="fullBorderCurve mainblur">
Fixed

2023-02-25 05:41 UTC, LoganDemaray316 commented on src/components/EventItemEdit.vue
> +                    variant="solo"></v-text-field>
The append icon had the effect of placing the icon outside of the text field. It is in this push

2023-02-25 05:42 UTC, LoganDemaray316 commented on src/components/EventItemEdit.vue
> +                  >//Addition Selections Go Here</v-card
Removed. There is nothing in here yet.

2023-02-25 05:43 UTC, LoganDemaray316 commented on src/components/EventItemEdit.vue
> +                      <v-card class="fullBorderCurve">
Done

2023-02-25 05:43 UTC, LoganDemaray316 commented on src/components/EventItemEdit.vue
> +                  <v-card class="eventsGradient fullBorderCurve mainblur">
Done

2023-02-25 05:47 UTC, LoganDemaray316 commented on src/components/EventItemEdit.vue
> +      timesToResults(start_time, end_time, interval) {
I'm not sure if I need to enter in different data, but I get an error saying it cannot use .getMinutes()

2023-02-25 05:48 UTC, LoganDemaray316 commented on src/components/EventItemEdit.vue
> +      timesToResults(start_time, end_time, interval) {
Uncaught (in promise) TypeError: startDate.getMinutes is not a function
    at Proxy.getTimeSlots (EventItemEdit.vue:252:33)
    at EventItemEdit.vue:67:41
    at Proxy.renderFnWithContext (runtime-core.esm-bundler.js:868:19)

2023-02-25 23:07 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +      timesToResults(start_time, end_time, interval) {
You just need to make sure `startDate, endDate` are JS Date datatypes. You may need to do some parsing prior to passing them into make sure they are.

2023-02-25 23:08 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +                    variant="solo"></v-text-field>
Weird - I can't pull this to look right now cause I am not at a point where I can switch branches. We can just leave it for now and deal with it in a later PR.

2023-02-26 03:02 UTC, ethanimooney approved these changes
LGTM, just remove the one comment

2023-02-26 03:02 UTC, ethanimooney commented on src/components/EventItemEdit.vue
> +        console.log(slots);
Can remove this

2023-02-26 04:37 UTC, merged