Adds real data to Critique Page
peyton-lalli/swe5-project-v3frontend pull request #97
Opened 2023-04-14 00:42 UTC by nathan-lalli

Adds most of the functionality to the critique page aside from actually making the critique itself.

- Gets the student for that sign up
- Gets the Instructor for that sign up
- Gets the Accompanist for that sign up
- Gets the jurors for that sign up
- Gets the Starting song that the student chose
- Gets the Student's repertoire for that sign up
- Gets all of the other data that is associated with the above

Also made some changes to a few of the services files to fix some bugs, name changes, and new functions added to the backend

- Adds an instrument service
- Adds the student instrument service
- Edits the accompanist service to add a get accompanist call
- Edits the eventsignup service to add a get signup by id call
- Edits the student instructor serivce to fix the typos
- Edits the student service file to add get student by their id call
- Edits the user store to change how the system gets the students for the instructor

2023-04-14 01:01 UTC, ethanimooney requested changes

2023-04-14 01:02 UTC, ethanimooney commented
Enjoy ... sorry friend

2023-04-14 01:06 UTC, nathan-lalli commented on src/components/Faculty/StudentComponent.vue
> +    async getStudents() {
I knew that, but it wouldn't let me sign in without getting this working first since it was a fatal error.

2023-04-14 01:06 UTC, nathan-lalli commented on src/components/Faculty/CritiqueListComponent.vue
> +    getTimeSlots(startDate, endDate, interval, place) {
What mixin file? Not sure what you are talking about

2023-04-14 01:07 UTC, nathan-lalli commented on src/components/Faculty/CritiqueListComponent.vue
> +      return dateTimeParse[0];
Same as above.

2023-04-14 01:07 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +    async getSongs() {
Hadn't thought about it. I will look into changing it.

Do you want it changed before I merge this? If not I will change it once the critique is fully functional.

2023-04-14 01:08 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +    async getStartingSong() {
Same thing/question as above.

2023-04-14 01:08 UTC, nathan-lalli commented on src/components/Faculty/CritiqueListComponent.vue
> +    async getStudents() {
Same thing/question as above.

2023-04-14 01:08 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +    async getJurors() {
I forgot you added that to the store. I will change this.

2023-04-14 01:09 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
I will look into doing that. Do you want it changed before I merge? If not I will change it once I have the create critique fully functional.

2023-04-14 01:09 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
Same question as above.

2023-04-14 01:09 UTC, ethanimooney commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +    async getSongs() {
It may be easier to just do it now - which I know is annoying but will be easier before adding more code.

2023-04-14 01:09 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
I forgot that you added that to the store. I will change it to use that instead.

2023-04-14 01:10 UTC, ethanimooney commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
It may be easier to just do it now - which I know is annoying but will be easier before adding more code.

2023-04-14 01:11 UTC, ethanimooney commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
It may be easier to just do it now - which I know is annoying but will be easier before adding more code.

2023-04-14 01:11 UTC, ethanimooney commented on src/components/Faculty/CritiqueListComponent.vue
> +    async getStudents() {
It may be easier to just do it now - which I know is annoying but will be easier before adding more code.

2023-04-14 01:12 UTC, nathan-lalli commented
> Enjoy ... sorry friend

You can't make me

2023-04-15 20:42 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
Done.

2023-04-15 20:47 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
Done.

2023-04-15 20:53 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +        });
Done.

2023-04-15 22:00 UTC, nathan-lalli commented on src/components/Faculty/CritiqueFacultyComponent.vue
> +    async getSongs() {
Done.

2023-04-15 22:09 UTC, nathan-lalli commented on src/components/Faculty/CritiqueListComponent.vue
> +    async getStudents() {
Done.

2023-04-15 22:30 UTC, nathan-lalli commented on src/components/Faculty/CritiqueListComponent.vue
> +    getTimeSlots(startDate, endDate, interval, place) {
The timeslot function in the mixins file is different than the one that I use because of the way the data is passed in

2023-04-15 22:30 UTC, nathan-lalli commented on src/components/Faculty/CritiqueListComponent.vue
> +      return dateTimeParse[0];
I added these to the mixin file.

2023-04-16 00:07 UTC, ethanimooney approved these changes
Looks good, thanks for making those changes

2023-04-16 01:30 UTC, merged